[tool.poetry]
name = "explosm-bot"
version = "1.0.0"
description = "A Twitter bot that prints randomly-generated comics"
authors = ["Alex The JPEG"]

[tool.poetry.dependencies]
python = "^3.10"
tweepy = "^4.12.1"
Pillow = "^9.3.0"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
